name: Checkmarx One Scan
on:
  push:
    branches:
      - main
      - master
      - dev
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      # required for all workflows
      security-events: write
      # only required for workflows in private repositories
      actions: read
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checkmarx One CLI Action
        #uses: checkmarx/ast-github-action@main #Github Action version
        uses: checkmarx/ast-github-action@2.0.9 #Github Action version
        with:
          #project_name: <Name of Checkmarx One Project>
          cx_tenant: apac-training
          base_uri: https://anz.ast.checkmarx.net/
          cx_client_id: ${{ secrets.CLIENT_ID }}
          cx_client_secret: ${{ secrets.SECRET }}
          # GitHub API Token
          github_token: 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
          #additional_params: --sast-incremental
          #additional_params: --threshold sast-high=5
          #additional_params: --tags test1 test2 --scan-types sast,sca,kics --file-filter !readme --report-format sarif --output-name results
          #additional_params: --report-format sarif --output-path .
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          # Path to SARIF file relative to the root of the repository
          sarif_file: cx_result.sarif
          
