name: Checkmarx One Scan
on:
  push:
    branches:
      - main
      - master
      - dev
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.09
      - name: Checkmarx One CLI Action
        #uses: checkmarx/ast-github-action@main #Github Action version
		uses: Checkmarx/ast-github-action@2.0.9
        with:
          #project_name: <Name of Checkmarx One Project>
          cx_tenant: apac-training
          base_uri: https://anz.ast.checkmarx.net/ 
          cx_client_id: ${{ secrets.CLIENT_ID }}
          cx_client_secret: ${{ secrets.SECRET }}
          additional_params: --threshold sast-high=20
